// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package foundation

import (
	"github.com/qhai-dev/ozma/foundation/application"
	"github.com/qhai-dev/ozma/foundation/infra/database"
	"github.com/qhai-dev/ozma/foundation/infra/opentelemetryx"
	"github.com/qhai-dev/ozma/foundation/infra/repository"
	"github.com/qhai-dev/ozma/foundation/transport/rpc"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	serverOption := opentelemetryx.NewOpenTelemetry()
	databaseDatabase, err := database.NewDatabase()
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(databaseDatabase)
	createUserHandler := application.NewCreateUserHandler(userRepository)
	userServer := rpc.NewUserServer(createUserHandler)
	server := rpc.NewGRPCServer(serverOption, userServer)
	app := NewApp(server)
	return app, nil
}
