// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID             int64
	Name           string
	NickName       pgtype.Text
	Email          pgtype.Text
	Phone          pgtype.Text
	Avatar         pgtype.Text
	HashPassword   pgtype.Text
	EnterPriseList []string
	DepartmentList []string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
