// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  name, phone, hash_password
) VALUES (
  $1, $2, $3
)
RETURNING id, name, nick_name, email, phone, avatar, hash_password, enter_prise_list, department_list, created_at, updated_at
`

type CreateUserParams struct {
	Name         string
	Phone        pgtype.Text
	HashPassword pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Phone, arg.HashPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NickName,
		&i.Email,
		&i.Phone,
		&i.Avatar,
		&i.HashPassword,
		&i.EnterPriseList,
		&i.DepartmentList,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, nick_name, email, phone, avatar, hash_password, enter_prise_list, department_list, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NickName,
		&i.Email,
		&i.Phone,
		&i.Avatar,
		&i.HashPassword,
		&i.EnterPriseList,
		&i.DepartmentList,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, nick_name, email, phone, avatar, hash_password, enter_prise_list, department_list, created_at, updated_at FROM users
ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NickName,
			&i.Email,
			&i.Phone,
			&i.Avatar,
			&i.HashPassword,
			&i.EnterPriseList,
			&i.DepartmentList,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
